import './global.css';

export const metadata = {
  title: 'Welcome to barista',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className='max-w-lg mx-auto'>
          {children}
        </div>
      </body>
    </html>
  );
}
