import './global.css';

export const metadata = {
  title: 'Welcome to barista',
  description: 'Generated by create-nx-workspace',
};

function BottomNavigation() {
  return <div className="btm-nav">
    <button className="text-primary">
1
    </button>
    <button className="text-primary active">
2
    </button>
    <button className="text-primary">
3
    </button>
  </div>;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className='max-w-lg mx-auto'>
          <main className='main-content'>
            {children}
          </main>
          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
