import { BottomNavigation } from '../components/BottomNavigation';
import './global.css';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className='max-w-lg mx-auto'>
          <main className='main-content'>
            {children}
          </main>
          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
